import type { NextPage } from 'next';
import Head from 'next/head';
import { HomeContainer, HomeMain } from '../styles/Home';

const Home: NextPage = () => {
  return (
    <HomeContainer>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <HomeMain>
        <h1>Hello</h1>
      </HomeMain>
    </HomeContainer>
  );
};

export default Home;
